(part "A6S-1102-H"
    (packageRef "A6S1102H")
    (interface
        (port "1" (symbPinId 1) (portName "COM") (portType INOUT))
        (port "2" (symbPinId 2) (portName "N.O.") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "653-A6S-1102-H")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/A6S-1102-H?qs=FFtkVBg2Ai6emF35RthuRw%3D%3D")
    (property "Manufacturer_Name" "OMRON Electronics")
    (property "Manufacturer_Part_Number" "A6S-1102-H")
    (property "Description" "Slide DIP Switch, Tube Packaging, Flat Type, With Seal Tape, 1-Pole")
    (property "Datasheet_Link" "https://components.omron.com/us-en/sites/components.omron.com.us/files/datasheet_pdf/A211-E1.pdf")
    (property "symbolName1" "A6S-1102-H")
)
