(part "S70KL1282DPBHI020"
    (packageRef "BGA24C100P5X5_600X800X100")
    (interface
        (port "A2" (symbPinId 1) (portName "RFU_1") (portType INOUT))
        (port "A3" (symbPinId 2) (portName "CS#") (portType INOUT))
        (port "A4" (symbPinId 3) (portName "RESET#") (portType INOUT))
        (port "A5" (symbPinId 4) (portName "RFU_2") (portType INOUT))
        (port "B1" (symbPinId 5) (portName "CK#") (portType INOUT))
        (port "B2" (symbPinId 6) (portName "CK") (portType INOUT))
        (port "B3" (symbPinId 7) (portName "VSS") (portType INOUT))
        (port "B4" (symbPinId 8) (portName "VCC") (portType INOUT))
        (port "B5" (symbPinId 9) (portName "RFU_3") (portType INOUT))
        (port "C1" (symbPinId 10) (portName "VSSQ_1") (portType INOUT))
        (port "C2" (symbPinId 11) (portName "RFU_4") (portType INOUT))
        (port "C3" (symbPinId 12) (portName "RWDS") (portType INOUT))
        (port "C4" (symbPinId 13) (portName "DQ2") (portType INOUT))
        (port "C5" (symbPinId 14) (portName "RFU_5") (portType INOUT))
        (port "D1" (symbPinId 15) (portName "VCCQ_1") (portType INOUT))
        (port "D2" (symbPinId 16) (portName "DQ1") (portType INOUT))
        (port "D3" (symbPinId 17) (portName "DQ0") (portType INOUT))
        (port "D4" (symbPinId 18) (portName "DQ3") (portType INOUT))
        (port "D5" (symbPinId 19) (portName "DQ4") (portType INOUT))
        (port "E1" (symbPinId 20) (portName "DQ7") (portType INOUT))
        (port "E2" (symbPinId 21) (portName "DQ6") (portType INOUT))
        (port "E3" (symbPinId 22) (portName "DQ5") (portType INOUT))
        (port "E4" (symbPinId 23) (portName "VCCQ_2") (portType INOUT))
        (port "E5" (symbPinId 24) (portName "VSSQ_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "727-70KL1282DPBHI020")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/S70KL1282DPBHI020?qs=DPoM0jnrROVgAEZ0o2TpIw%3D%3D")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "S70KL1282DPBHI020")
    (property "Description" "DRAM HyperRAM")
    (property "Datasheet_Link" "https://www.cypress.com/file/501841/download")
    (property "symbolName1" "S70KL1282DPBHI020")
)
