(part "OPA2134UAE4"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT_A") (portType INOUT))
        (port "2" (symbPinId 2) (portName "–IN_A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN_A") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "+IN_B") (portType INOUT))
        (port "6" (symbPinId 6) (portName "–IN_B") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT_B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "V+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-OPA2134UAE4")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA2134UAE4?qs=7nS3%252BbEUL6uzphh9X3AzMA%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA2134UAE4")
    (property "Description" "TEXAS INSTRUMENTS - OPA2134UAE4. - Audio Power Amplifier, 2 Channel, +/- 2.5V to +/- 18V, SOIC, 8 Pins")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/OPA2134")
    (property "symbolName1" "OPA2134UAE4")
)
