(part "2908-05WB-MG"
    (packageRef "290805WBMG")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "MP1" (symbPinId 9) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 10) (portName "MP2") (portType INOUT))
        (port "MP3" (symbPinId 11) (portName "MP3") (portType INOUT))
        (port "MP4" (symbPinId 12) (portName "MP4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "517-2908-05WB-MG")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/3M-Electronic-Solutions-Division/2908-05WB-MG?qs=vnwGVgFuQiZPJoOt79ALlw%3D%3D")
    (property "Manufacturer_Name" "3M")
    (property "Manufacturer_Part_Number" "2908-05WB-MG")
    (property "Description" "Memory Card Connectors MICROSD 8P P/P SMT POLARIZED")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/2908-05WB-MG.pdf")
    (property "symbolName1" "2908-05WB-MG")
)
